version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloudusers
      MYSQL_USER: veryval
      MYSQL_PASSWORD: 12398755
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  app:
    image: cloudserver:latest
    container_name: app
    restart: always
    ports:
      - 5500:5500
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/cloudusers
      - spring.datasource.username=veryval
      - spring.datasource.password=12398755
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.sql.init.mode=always
      - spring.sql.init.data-locations=classpath:data.sql
      - server.port=5500
      - allowed.uri.localhost=http://localhost:8080
      - spring.jpa.hibernate.show_sql=true
      - spring.jpa.hibernate.ddl-auto=none
      - jwt_secret=mySecretKey
    depends_on:
      - db